from typing import List, Dict, TypedDict, Annotated
from langgraph.graph import StateGraph, END, START
from dotenv import load_dotenv  
from langchain_google_genai import ChatGoogleGenerativeAI  
from pydantic import BaseModel, Field  
import operator
import os

load_dotenv()
google_gemini_api_key = os.getenv("api_key")

model = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0.3, api_key=google_gemini_api_key)

class evalschema(BaseModel):
    feedback: str = Field(description="Feedback on the response generated by the model")
    score: int = Field(description="Score for the response generated by the model, on a scale of 1 to 10")

structured_model = model.with_structured_output(evalschema)

def get_user_input():
    """Get content to evaluate from the user."""
    print("\n" + "="*60)
    print("ESSAY/CONTENT EVALUATION SYSTEM")
    print("="*60)
    print("\nEnter the content you want to evaluate (press Enter twice when done):")
    print("-" * 60)
    
    lines = []
    empty_line_count = 0
    
    while True:
        line = input()
        if line == "":
            empty_line_count += 1
            if empty_line_count >= 2:
                break
            lines.append(line)
        else:
            empty_line_count = 0
            lines.append(line)
    
    content = "\n".join(lines).strip()
    
    if not content:
        print("\nNo content provided. Using default essay...")
        content = """Medical ethics is the moral framework guiding healthcare professionals in making fair, compassionate, and responsible decisions. It is built on core principles such as autonomy, beneficence, non-maleficence, and justice. Autonomy respects a patient's right to make informed choices, while beneficence ensures actions are taken for the patient's well-being. Non-maleficence emphasizes "do no harm," and justice promotes fairness in treatment. In today's world of rapid medical advancements, ethical considerations help balance technology with humanity. Upholding medical ethics fosters trust between doctors and patients, ensuring that care is not only effective but also respectful, dignified, and morally sound."""
    
    return content

class UPSCstate(TypedDict):
    essay: str
    language_feedback: str
    analysis_feedback: str
    clarity_feedback: str
    overall_feedback: str
    individual_scores: Annotated[list[int], operator.add]
    avg_score: float

def eval_lang(state: UPSCstate):
    """
    Role-based Language Evaluation
    Evaluates grammar, vocabulary, sentence structure, and writing style.
    """
    prompt = f"""You are an expert language and writing specialist with extensive experience in academic and professional writing evaluation.

YOUR ROLE:
- Assess the quality of language, grammar, vocabulary, and writing style
- Evaluate sentence structure, clarity, and readability
- Identify strengths and areas for improvement in linguistic expression
- Provide constructive feedback for enhancement

CONTENT TO EVALUATE:
{state['essay']}

EVALUATION CRITERIA:
1. Grammar and Syntax: Correct usage, punctuation, sentence construction
2. Vocabulary: Word choice appropriateness, variety, and precision
3. Clarity: Ease of understanding, logical flow, coherence
4. Writing Style: Tone, voice, professionalism appropriate to context

Provide specific feedback and assign a score out of 10."""
    
    output = structured_model.invoke(prompt)
    return {'language_feedback': output.feedback, 'individual_scores': [output.score]}

def eval_analysis(state: UPSCstate):
    """
    Role-based Content Analysis Evaluation
    Evaluates depth of analysis, critical thinking, and argument quality.
    """
    prompt = f"""You are a subject matter expert and critical thinking specialist experienced in evaluating analytical depth and argument quality.

YOUR ROLE:
- Assess the depth and quality of analysis presented
- Evaluate evidence, reasoning, and logical argumentation
- Identify strengths of critical thinking and analytical approach
- Highlight areas where deeper analysis is needed

CONTENT TO EVALUATE:
{state['essay']}

EVALUATION CRITERIA:
1. Depth of Analysis: Goes beyond surface-level observations
2. Evidence Quality: Relevant, credible, and well-integrated examples
3. Critical Thinking: Questions assumptions, explores multiple perspectives
4. Logical Framework: Clear progression of ideas, sound reasoning
5. Originality: Unique insights and perspectives presented

Provide specific feedback and assign a score out of 10."""
    
    output = structured_model.invoke(prompt)
    return {'analysis_feedback': output.feedback, 'individual_scores': [output.score]}

def eval_thought(state: UPSCstate):
    """
    Role-based Clarity and Coherence Evaluation
    Evaluates logical flow, organization, and clarity of thought.
    """
    prompt = f"""You are an experienced academic advisor and content organizer specializing in evaluating clarity and coherence of written communication.

YOUR ROLE:
- Assess clarity of thought and expression throughout the content
- Evaluate organizational structure and logical flow
- Identify confusion points and areas requiring clarification
- Ensure ideas are presented in a coherent, easy-to-follow manner

CONTENT TO EVALUATE:
{state['essay']}

EVALUATION CRITERIA:
1. Clarity: Ideas are expressed clearly and unambiguously
2. Organization: Logical structure with clear introduction, body, conclusion
3. Coherence: Smooth transitions between ideas and paragraphs
4. Focus: Main arguments are clear and well-supported
5. Reader Experience: Easy for audience to follow and understand the message

Provide specific feedback and assign a score out of 10."""
    
    output = structured_model.invoke(prompt)
    return {'clarity_feedback': output.feedback, 'individual_scores': [output.score]}

def final_eval(state: UPSCstate):
    """
    Role-based Comprehensive Evaluation Summary
    Synthesizes all evaluations into actionable recommendations.
    """
    avg_score = sum(state['individual_scores']) / len(state['individual_scores'])
    
    prompt = f"""You are a senior academic evaluator and content assessment specialist responsible for synthesizing comprehensive feedback.

YOUR ROLE:
- Create a cohesive summary of all evaluation aspects
- Synthesize feedback from language, analysis, and clarity assessments
- Provide prioritized recommendations for improvement
- Highlight key strengths to build upon

INDIVIDUAL EVALUATIONS RECEIVED:
1. Language & Writing Quality Feedback: {state['language_feedback']}
2. Analytical Depth Feedback: {state['analysis_feedback']}
3. Clarity & Coherence Feedback: {state['clarity_feedback']}

INDIVIDUAL SCORES: {state['individual_scores']}
AVERAGE SCORE: {avg_score:.1f}/10

TASK:
Provide a comprehensive summary that:
- Highlights overall strengths
- Identifies key areas for improvement (prioritized)
- Offers specific, actionable recommendations
- Considers all three evaluation dimensions holistically
- Maintains a constructive and encouraging tone

The feedback should be valuable, specific, and motivating for the writer."""
    
    overall_feedback = model.invoke(prompt)
    
    return {'overall_feedback': overall_feedback, 'avg_score': avg_score}

# Adding nodes
graph = StateGraph(UPSCstate)
graph.add_node("evaluate_language", eval_lang)
graph.add_node("evaluate_analysis", eval_analysis)
graph.add_node("evaluate_thought", eval_thought)
graph.add_node("final_eval", final_eval)

# Adding edges
graph.add_edge(START, "evaluate_language")
graph.add_edge(START, "evaluate_analysis")
graph.add_edge(START, "evaluate_thought")

graph.add_edge("evaluate_language", "final_eval")
graph.add_edge("evaluate_analysis", "final_eval")
graph.add_edge("evaluate_thought", "final_eval")
graph.add_edge('final_eval', END)

workflow = graph.compile()

# Execute the workflow
if __name__ == "__main__":
    # Get user input
    essay = get_user_input()
    
    print("\n" + "="*60)
    print("PROCESSING YOUR CONTENT...")
    print("="*60)
    print("\nAnalyzing language, depth of analysis, and clarity...")
    
    initial_state = {
        "essay": essay
    }
    
    result = workflow.invoke(initial_state)
    
    # Display results
    print("\n" + "="*60)
    print("EVALUATION RESULTS")
    print("="*60)
    
    print(f"\n LANGUAGE & WRITING QUALITY:")
    print("-" * 60)
    print(result['language_feedback'])
    
    print(f"\n ANALYTICAL DEPTH:")
    print("-" * 60)
    print(result['analysis_feedback'])
    
    print(f"\n CLARITY & COHERENCE:")
    print("-" * 60)
    print(result['clarity_feedback'])
    
    print("\n" + "="*60)
    print("COMPREHENSIVE FEEDBACK")
    print("="*60)
    print(result['overall_feedback'])
    
    print(f"\n{'AVERAGE SCORE:':<20} {result['avg_score']:.1f}/10")
    print("="*60 + "\n")